spring:
  application:
    name: myai
  data:
    redis:
      host: 192.168.187.128
      port: 6379
      database: 3
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index: spring_ai_index
        prefix: "doc:"
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myai?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepstmts=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.lbl.myai: debug

